---
title: "Proyecto final R, capacitación hidrobiología"
author: "Zury Carcamo"
format: html
editor: visual
---

::: panel-tabset
## Asignación clase 1

Ingreso de datos, Limpieza y filtrado de datos

#cargar paquete

```{r}
library(tidyverse)
```

#cargar base de datos

```{r}
penguins<- read.csv("data/penguins_size.csv")
```

#Filtrado de datos

```{r}
penguinsSexoHembra<-penguins %>%
  filter(sex== "FEMALE")
table(penguinsSexoHembra$sex)
```

#Visualizar las islas

```{r}
table(penguins$island)

 table(penguins$sex) 

table(penguins$species)
```

#Seleccionar variables

```{r}
penguins2<- penguins %>% 
  select(island) %>% 
  filter(island=="Dream") 
head(penguins2) str(penguins2)
table(penguins2$island)
```

#resumen por sexo y por isla

```{r}
penguinsS<- penguins %>%
  group_by(island, sex) %>%
  summarise(mediapeso= mean(body_mass_g)) 
penguinsS
```

## Asignación clase 2

Uso R Markdow y visualización de datos

## Asignación clase 3

Procesamiento de datos

## Quarto

Listo!
:::
